### ISSUE TITLE
dnscrypt-proxy git build crash+trace on access

### ISSUE THREAD

**Issue by pgnd** [jedisct1/dnscrypt-proxy#271]
using dnsscrypt-proxy from git src,
```
	cd /usr/local/src/dnscrypt-proxy
	git log | head
		commit 63ae08fa00db24a79abc9abcbea9178872fefdd1
		Author: Frank Denis <github@pureftpd.org>
		Date:   Sun Aug 23 12:29:39 2015 +0200

		    Add /run/systemd/notify to the apparmor rules

		commit 3edc1ed22bfbd88ff903f465be126c1faa417d7d
		Author: Frank Denis <github@pureftpd.org>
		Date:   Sat Aug 22 09:54:21 2015 +0200
```
on opensuse
```
	lsb_release -rd
		Description:    openSUSE 13.2 (Harlequin) (x86_64)
		Release:        13.2
	gcc --version
		gcc (SUSE Linux) 5.2.1 20150721 [gcc-5-branch revision 226027]
```
building
```
	./autogen.sh
	./configure \
	--prefix=/usr/local/dnscrypt-proxy \
	--enable-plugins \
	--enable-shared --disable-static \
	--with-systemd \
	--with-gnu-ld
	make
	make install
```
No reported errors in build.
```
	ldd /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy
	        linux-vdso.so.1 (0x00007ffca3bdf000)
	        libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007f7664222000)
	        libltdl.so.7 => /usr/lib64/libltdl.so.7 (0x00007f7664018000)
	        libsodium.so.13 => /usr/lib64/libsodium.so.13 (0x00007f7663dc3000)
	        libdl.so.2 => /lib64/libdl.so.2 (0x00007f7663bbf000)
	        libm.so.6 => /lib64/libm.so.6 (0x00007f76638be000)
	        libc.so.6 => /lib64/libc.so.6 (0x00007f7663516000)
	        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f76632ed000)
	        libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007f7663009000)
	        libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007f7662df7000)
	        librt.so.1 => /lib64/librt.so.1 (0x00007f7662bef000)
	        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f76629d8000)
	        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f76627ba000)
	        /lib64/ld-linux-x86-64.so.2 (0x00005623ddc7e000)

	/usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy --version
		dnscrypt-proxy 1.6.0
```
picking/testing a single resolver
```
	mv dnscrypt-resolvers.csv dnscrypt-resolvers.csv.ORIG
	egrep -i "^cisco," dnscrypt-resolvers.csv.ORIG> dnscrypt-resolvers.csv

	sh -x /usr/local/src/dnscrypt-proxy*/resolvers-check.sh

	cat dnscrypt-online-resolvers.csv
		cisco,Cisco OpenDNS,Remove your DNS blind spot,Anycast,,https://www.opendns.com,1,no,no,no,208.67.220.220:443,2.dnscrypt-cert.opendns.com,B735:1140:206F:225D:3E2B:D822:D7FD:691E:A1C3:3CC8:D666:8D0C:BE04:BFAB:CA43:FB79,

	mv dnscrypt-online-resolvers.csv /usr/local/etc/dnscrypt-proxy/
```
Using systemd unit files
```
	cat /etc/systemd/system/dnscrypt-proxy.service
		[Unit]
		Description=DNSCrypt client proxy
		Requires=dnscrypt-proxy.socket

		[Service]
		Type=simple
		NonBlocking=true
		ExecStart=/usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy \
		          --logfile=/var/log/dnscrypt-proxy/dnscrypt-proxy.log \
		          --loglevel=6 \
		          --edns-payload-size=4096 \
		          --resolvers-list=/usr/local/etc/dnscrypt-proxy/dnscrypt-online-resolvers.csv \
		          --resolver-name=cisco

		[Install]
		Also=dnscrypt-proxy.socket
		WantedBy=multi-user.target

	cat /etc/systemd/system/dnscrypt-proxy.socket
		[Unit]
		Description=dnscrypt-proxy listening socket
		After=network-online.target

		[Socket]
		ListenStream=127.0.0.1:10153
		ListenDatagram=127.0.0.1:10153

		[Install]
		WantedBy=sockets.target
```
Starting
```
	systemctl daemon-reload
	systemctl enable dnscrypt-proxy.service dnscrypt-proxy.socket
	systemctl start dnscrypt-proxy.socket

	@ journalctl -f 
		...
		Aug 23 16:29:50 dev.loc systemd[1]: Starting dnscrypt-proxy listening socket.
		Aug 23 16:29:50 dev.loc systemd[1]: Listening on dnscrypt-proxy listening socket.
```
No service 'up'
```
	ps ax | grep dnsc
		22193 pts/0    S+     0:00 grep --color=auto dnsc
```
@ test of availability/access
```
	telnet 127.0.0.1 10153
```
get a crash + stack trace, and some systemd flailing
```
	@ journalctl -f
		...
		Aug 23 16:32:07 dev.loc systemd[1]: Starting DNSCrypt client proxy...
		Aug 23 16:32:07 dev.loc systemd[1]: Started DNSCrypt client proxy.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: Signal [11] received.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: ======== Stack trace ========
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x8613) [0x55a9355c1613]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: /lib64/libc.so.6(+0x35200) [0x7fb74ab57200]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x2695f) [0x55a9355df95f]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x71e1) [0x55a9355c01e1]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x7b17) [0x55a9355c0b17]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x4a91) [0x55a9355bda91]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fb74ab43b05]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23891]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x45fc) [0x55a9355bd5fc]
		Aug 23 16:32:07 dev.loc systemd[1]: dnscrypt-proxy.service: main process exited, code=killed, status=11/SEGV
		Aug 23 16:32:07 dev.loc systemd[1]: Unit dnscrypt-proxy.service entered failed state.
		Aug 23 16:32:07 dev.loc systemd[1]: Starting DNSCrypt client proxy...
		Aug 23 16:32:07 dev.loc systemd[1]: Started DNSCrypt client proxy.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: Signal [11] received.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: ======== Stack trace ========
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x8613) [0x5611dc8e1613]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: /lib64/libc.so.6(+0x35200) [0x7f4624631200]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x2695f) [0x5611dc8ff95f]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x71e1) [0x5611dc8e01e1]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x7b17) [0x5611dc8e0b17]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x4a91) [0x5611dc8dda91]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f462461db05]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23893]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x45fc) [0x5611dc8dd5fc]
		Aug 23 16:32:07 dev.loc systemd[1]: dnscrypt-proxy.service: main process exited, code=killed, status=11/SEGV
		Aug 23 16:32:07 dev.loc systemd[1]: Unit dnscrypt-proxy.service entered failed state.
		Aug 23 16:32:07 dev.loc systemd[1]: Starting DNSCrypt client proxy...
		Aug 23 16:32:07 dev.loc systemd[1]: Started DNSCrypt client proxy.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: Signal [11] received.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: ======== Stack trace ========
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x8613) [0x55aec5da2613]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: /lib64/libc.so.6(+0x35200) [0x7f756b688200]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x2695f) [0x55aec5dc095f]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x71e1) [0x55aec5da11e1]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x7b17) [0x55aec5da1b17]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x4a91) [0x55aec5d9ea91]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f756b674b05]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23895]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x45fc) [0x55aec5d9e5fc]
		Aug 23 16:32:07 dev.loc systemd[1]: dnscrypt-proxy.service: main process exited, code=killed, status=11/SEGV
		Aug 23 16:32:07 dev.loc systemd[1]: Unit dnscrypt-proxy.service entered failed state.
		Aug 23 16:32:07 dev.loc systemd[1]: Starting DNSCrypt client proxy...
		Aug 23 16:32:07 dev.loc systemd[1]: Started DNSCrypt client proxy.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: Signal [11] received.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: ======== Stack trace ========
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x8613) [0x556f942cf613]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: /lib64/libc.so.6(+0x35200) [0x7ff71e46f200]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x2695f) [0x556f942ed95f]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x71e1) [0x556f942ce1e1]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x7b17) [0x556f942ceb17]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x4a91) [0x556f942cba91]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: /lib64/libc.so.6(__libc_start_main+0xf5) [0x7ff71e45bb05]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23897]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x45fc) [0x556f942cb5fc]
		Aug 23 16:32:07 dev.loc systemd[1]: dnscrypt-proxy.service: main process exited, code=killed, status=11/SEGV
		Aug 23 16:32:07 dev.loc systemd[1]: Unit dnscrypt-proxy.service entered failed state.
		Aug 23 16:32:07 dev.loc systemd[1]: Starting DNSCrypt client proxy...
		Aug 23 16:32:07 dev.loc systemd[1]: Started DNSCrypt client proxy.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: Signal [11] received.
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: ======== Stack trace ========
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x8613) [0x555e798e7613]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: /lib64/libc.so.6(+0x35200) [0x7f2df2e34200]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x2695f) [0x555e7990595f]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x71e1) [0x555e798e61e1]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x7b17) [0x555e798e6b17]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x4a91) [0x555e798e3a91]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f2df2e20b05]
		Aug 23 16:32:07 dev.loc dnscrypt-proxy[23899]: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy(+0x45fc) [0x555e798e35fc]
		Aug 23 16:32:07 dev.loc systemd[1]: dnscrypt-proxy.service: main process exited, code=killed, status=11/SEGV
		Aug 23 16:32:07 dev.loc systemd[1]: Unit dnscrypt-proxy.service entered failed state.
		Aug 23 16:32:07 dev.loc systemd[1]: Starting DNSCrypt client proxy...
		Aug 23 16:32:07 dev.loc systemd[1]: dnscrypt-proxy.service start request repeated too quickly, refusing to start.
		Aug 23 16:32:07 dev.loc systemd[1]: Failed to start DNSCrypt client proxy.
		Aug 23 16:32:07 dev.loc systemd[1]: Unit dnscrypt-proxy.socket entered failed state.
```

**Comment by pgnd** [comment]
gdb trace
```
Starting program: /usr/local/dnscrypt-proxy/sbin/dnscrypt-proxy -L /usr/local/etc/dnscrypt-proxy/dnscrypt-online-resolvers.csv -R cisco
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555557a96f in evutil_ascii_strcasecmp ()
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7f9b780 (LWP 10754)):
#0  0x000055555557a96f in evutil_ascii_strcasecmp ()
#1  0x000055555555b1e1 in options_parse_resolvers_list ()
#2  0x000055555555bb17 in options_parse ()
#3  0x0000555555558a91 in dnscrypt_proxy_main ()
#4  0x00007ffff70f4b05 in __libc_start_main (main=0x5555555585a1 <main>, argc=5, argv=0x7fffffffd5e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffd5d8) at libc-start.c:285
#5  0x00005555555585fc in _start () at ../sysdeps/x86_64/start.S:112
(gdb) bt full
#0  0x000055555557a96f in evutil_ascii_strcasecmp ()
No symbol table info available.
#1  0x000055555555b1e1 in options_parse_resolvers_list ()
No symbol table info available.
#2  0x000055555555bb17 in options_parse ()
No symbol table info available.
#3  0x0000555555558a91 in dnscrypt_proxy_main ()
No symbol table info available.
#4  0x00007ffff70f4b05 in __libc_start_main (main=0x5555555585a1 <main>, argc=5, argv=0x7fffffffd5e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffd5d8) at libc-start.c:285
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 4618326909441918, 93824992249299, 140737488344544, 0, 0, -4618328190167170, -4637436921587842}, mask_was_saved = 0}}, priv = {pad = {
              0x0, 0x0, 0x7fffffffd618, 0x7ffff7ffe148}, data = {prev = 0x0, cleanup = 0x0, canceltype = -10728}}}
        not_first_call = <optimized out>
#5  0x00005555555585fc in _start () at ../sysdeps/x86_64/start.S:112
No locals.
(gdb) 
```

**Comment by jedisct1** [comment]
Columns headers are missing in your CSV file.

Error handling for this kind of invalid file has been added in 90e9d0ead6b7e6093a2d0b90778c6b8f0b4f36a4 ; thanks for reporting this!
