### ISSUE TITLE
force_tcp = true / Up udp  socket ? 

### ISSUE THREAD

**Issue by Sitisk** [jedisct1/dnscrypt-proxy#487]
Hello.
1) If in *.toml configuration force_tcp = true . Dnscrypt running udp and tcp socket. 

dig @127.0.0.1 google.com 
Perfectly communicates on UDP protocol, despite the stated. 
'## Always use TCP to connect to upstream servers.'
**Way ?  Maybe we should start only tcp socket listen.?**

2) if in  *.toml file added proxy = "socks5://127.0.0.1:9050" . 
and dig @127.0.0.1 google.com 
Crashing dnscrypt. Log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7deb85]

goroutine 21 [running]:
main.(*Proxy).exchangeWithTCPServer(0xc420142018, 0xc4201a0000, 0xc4201761a0, 0xc4201c80c0, 0xc0, 0xc0, 0xc420188110, 0xc, 0xc, 0xc0, ...)
	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:225 +0xf5
main.(*Proxy).processIncomingQuery(0xc420142018, 0xc4201a0000, 0x8d6d47, 0x3, 0x8d6d41, 0x3, 0xc4201a6000, 0x2b, 0xfff, 0xc42002d9e0, ...)
	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:295 +0xcbc
main.(*Proxy).udpListener.func1(0xc420142018, 0xc4201a6000, 0x2b, 0xfff, 0xc42002d9e0, 0xc420190000)
	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:149 +0x10e
created by main.(*Proxy).udpListener
	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:143 +0x9a
```
dnscrypt-proxy 2.0.15

**Comment by jedisct1** [comment]
Clients will always use UDP, and will not automatically fall back to TCP. So, the UDP listening socket is required.
